#!/usr/bin/env bash
# fizzbuzz

for ((count = 1; count < 101; count++));do
	if [ $((count % 3)) -eq 0 ] && [ $((count % 5)) -eq 0 ];then
		echo "FizzBuzz"
	elif [ $((count % 3)) -eq 0 ];then
		echo "Fizz"
	elif [ $((count % 5)) -eq 0 ];then
		echo "Buzz"
	else
		echo "$count"
	fi
done
