#!/usr/bin/env bash
# displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi
count=0
while [ $count -le 9 ]; do
	echo "Best School"
	if [ $count -eq 8 ]; then
		echo "Hi"
	fi
	((count++))
done
