#!/usr/bin/env bash
# bad luck good luck script
count=0
while [ $count -le 9 ]; do
	if [ $count -eq 3 ]; then
		echo "bad luck"
	elif [ $count -eq 7 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((count++))
done
