#!/usr/bin/env bash
#  9-to_file_or_not_to_file
file="school"

if [ -d "$file" ]; then
	echo "school file exists"
	if [ -z "$(ls -A $file)" ];then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi
elif [ -f "$file" ]; then
	echo "school file exists"
	if [ -s "$file" ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	echo "school is a regular file"
else
	echo "school file does not exist"
fi
